#!/usr/bin/env bash
# Start local dev stack for pharma-ai (run each service in its own terminal).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"

echo "Pharma AI — local development"
echo "Repo: $ROOT"
echo ""
echo "Run these in separate terminals:"
echo ""
echo "1) Vector DB (once):"
echo "   cd $ROOT/ai-service && docker compose up -d qdrant"
echo ""
echo "2) AI service :9000"
echo "   cd $ROOT/ai-service"
echo "   python3 -m venv .venv  # first time only"
echo "   .venv/bin/pip install -r requirements.txt"
echo "   .venv/bin/uvicorn app.main:app --port 9000 --reload"
echo ""
echo "3) Laravel API :8000"
echo "   cd $ROOT/backend"
echo "   cp .env.example .env  # first time; set AI_SERVICE_URL=http://localhost:9000"
echo "   php artisan serve --port=8000"
echo ""
echo "4) Frontend :3000"
echo "   cd $ROOT/frontend"
echo "   cp .env.local.example .env.local  # NEXT_PUBLIC_BACKEND_URL=http://localhost:8000"
echo "   npm install && npm run dev"
echo ""
echo "Optional — ingest PDFs into SQLite + Qdrant:"
echo "   cd $ROOT/ai-service && .venv/bin/python -m app.ingestion.run_ingest"
echo ""
echo "Health: http://localhost:8000/api/health/ready"
echo "Corpus: http://localhost:3000/corpus"
